# Execute on push to main 
# TODO: Customise further 
on:
  push:
    #branches: [main]

jobs: 
  update_docs_deployment: # name of job
    runs-on: ubuntu-latest # what virtual machine job runs on
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps: # Steps from the point of view of the virtual machine (defined by 'runs-on')
      - name: Checkout
        uses: actions/checkout@v2.3.4 # one of githubs default actions
    
      - name: Set up python
        uses: actions/setup-python@v2.2.1 # another of githubs default actions
        with: 
          python-version: 3.9

      - name: Install dependencies 
        run: | # Use pipe to run multiple lines so can also install read the docs theme
          python -m pip install sphinx
          python -m pip install sphinx-rtd-theme 
          python -m pip install ghp-import
      
      - name: Make sphinx documentation 
        run: |
          sphinx-autodoc -o ./docs .
          cd ./docs
          make html

      - name: Run ghp-import 
        run: |
          ghp-import -n -p -f ./docs/_build/html 
      # - name: Init new repo in dist dir and commit files generated in docs/_build
      #   run: |
      #     cd ./docs/_build/html/
      #     git init 
      #     touch .nojekyll
      #     git add -A
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "Github Action"
      #     git commit -m "Deploy documentation"

      # - name: Force push to destination branch (gh-pages)
      #   uses: ad-m/github-push-action@v0.5.0
      #   with: 
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: gh-pages
      #     force: true
      #     directory: ./docs/_build/html

# NB: .nojekyll since otherwise github uses jekyll which ignores /docs/_* directories
# directory: ./docs/_build/html explains where I am pushing from

#          make -C docs clean 
#          make -C docs html